### ISSUE TITLE
test dataset

### ISSUE THREAD

**Issue by xuemo188** [cddlyf/GCANet#11]
Hi, thank you very much for your code, I am already learning it. However, this error was reported when running train.py.
 
![2f2219ed3ee30ae297e45e20c75c0e3](https://user-images.githubusercontent.com/55520460/74099488-4b912080-4b5f-11ea-99af-5143d92b6c62.png)

Say that the input size of the test data does not match the size of the label. I follow the test dataset RESIDE-Standard SOTS indoor dataset mentioned in your paper.
 
![55dcd77cd53a2d455dc6aa3f9fd79da](https://user-images.githubusercontent.com/55520460/74099490-551a8880-4b5f-11ea-8ef8-e9b58be4b9a9.png)

I found that the size of the hazy in this SOTS indoor dataset is 620x460, but the gt is 640x480. Have you encountered this problem? How did you solve it?

**Comment by xuemo188** [comment]
Hi, thank you very much for your code, I am already learning it. However, this error was reported when running train.py.

![image](https://user-images.githubusercontent.com/55520460/74099504-8430fa00-4b5f-11ea-9f07-afd1cdf89baa.png)


Say that the input size of the test data does not match the size of the label. I follow the test dataset RESIDE-Standard SOTS indoor dataset mentioned in your paper.
![image](https://user-images.githubusercontent.com/55520460/74099507-957a0680-4b5f-11ea-8709-17b439342154.png)

I found that the size of the hazy in this SOTS indoor dataset is 620x460, but the gt is 640x480. Have you encountered this problem? How did you solve it?

**Comment by cddlyf** [comment]
For the SOTS dataset problem, please ask the author of SOTS, I guess they will give the best answer for it. For my implementation, if the input size is not the multiplier of 4, I will resize it slightly.
