### ISSUE TITLE
Something about test set

### ISSUE THREAD

**Issue by 2014ZDH** [cddlyf/GCANet#12]
Hi author, does your test dataset use the RESIDE standard dataset (SOTS indoor dataset)? I hope to get your answer as soon as possible, thank you.

**Comment by cddlyf** [comment]
I think the answer is yes, if I remember it correctly( I do not do research about dehazing task anymore).

**Comment by 2014ZDH** [comment]
> I think the answer is yes, if I remember it correctly( I do not do research about dehazing task anymore).

Thank you.
