### ISSUE TITLE
issues about SOTS dataset？

### ISSUE THREAD

**Issue by liang233** [cddlyf/GCANet#2]
hello，the size of gt is not same with the size of hazy image，can I resize hazy image before test，or resize dehaze image after test，or both resize gt and hazy image？
I resize dehaze image after test the SOTS indoor datset ，（620**460->640**480）,but I only get psnr about 14, how to solve the problem.
this is the psnr matlab code I use:
https://paste.ubuntu.com/p/4s7mpv5MCG/

**Comment by cddlyf** [comment]
I have not observed the size mis-match problem, are you sure that you have downloaded the correct dataset? or could you give an example?

For the PSNR, I just use the self-contained psnr function of matlab [https://www.mathworks.com/help/images/ref/psnr.html](url)

**Comment by liang233** [comment]
hello，I dowload SOTS datsset from https://github.com/Boyiliee/RESIDE-dataset-link ，SOTS indoor  dataset，
![default](https://user-images.githubusercontent.com/8869756/50624794-59d53c00-0f5e-11e9-8999-ea8104efcf38.png)
![default](https://user-images.githubusercontent.com/8869756/50624802-66f22b00-0f5e-11e9-8b29-38534abec385.png)

**Comment by cddlyf** [comment]
Though I don't know what error happened  in you issue, I don't find this problem in my downloaded version. You can access it at [https://pan.baidu.com/s/16IInkL-KVJWfME2iBBCsAA](url)

**Comment by liang233** [comment]
thank you very much.
