### ISSUE TITLE
something aboat  training set

### ISSUE THREAD

**Issue by xianglei96** [cddlyf/GCANet#3]
I tested the RESIDE with the pre-trained model you gave and found that the outdoor image is not as good as the indoor image, so I want to know if the training datasets you use contains outdoor images.I hope to get your answer as soon as possible, thank you.

**Comment by cddlyf** [comment]
Hi lei, I just use the RESIDE standard dataset (ITS) as previous methods for training, which only contains indoor images.

**Comment by lake0502** [comment]
There are two versions of the RESIDE dataset (ITS) as shown below, one with 110,000 images and the other with 13,990 images. Which one did you choose to train the model? 
Thank you. 

https://sites.google.com/view/reside-dehaze-datasets/reside-v0 (ITS-110,000 images)
https://sites.google.com/view/reside-dehaze-datasets/reside-standard (ITS-13,990 images)

**Comment by cddlyf** [comment]
@lake0502 In my memory, it should be the second one (13990 images).

**Comment by 2014ZDH** [comment]
> I tested the RESIDE with the pre-trained model you gave and found that the outdoor image is not as good as the indoor image, so I want to know if the training datasets you use contains outdoor images.I hope to get your answer as soon as possible, thank you.

Hello, did you test in the RESIDE standard dataset (SOTS) indoor dataset? What are the values of PSNR and SSIM that you tested with the pre-trained model given by the author?

**Comment by SunLeL** [comment]
你好，我使用您提供的模型分别训练了室内和室外的数据集，室外数据集的训练结果还算正常，可是室内数据集（13990张）的效果却挺不好，psnr值都到不了20

**Comment by SunLeL** [comment]
Hello, I used the model you provided to train the indoor and outdoor data sets respectively. The training results of the outdoor data sets are normal, but the effect of the indoor data sets (13990 pieces) is very poor, and the PSNR value is less than 20？
