### ISSUE TITLE
something about training 

### ISSUE THREAD

**Issue by l172293793** [cddlyf/GCANet#8]
I use your network to train the model, but it goes wrong.
![image](https://user-images.githubusercontent.com/33507581/62342769-9f6cde00-b51a-11e9-881c-e1dcf2f105e6.png)
Can you tell me how to solve it?

**Comment by cddlyf** [comment]
It seems to be your setting problem or data problem, please debug it and see what settings are wrong.

**Comment by l172293793** [comment]
> It seems to be your setting problem or data problem, please debug it and see what settings are wrong.

I referenced your network on my training program, and any training program that reported an error was the same. Can you send me your training program?

**Comment by dochenms** [comment]
Are you sure you set the inc and outc correctly?

class GCANet(nn.Module):
    def __init__(self, in_c=4, out_c=3, only_residual=True):

**Comment by l172293793** [comment]
> Are you sure you set the inc and outc correctly?
> 
> class GCANet(nn.Module):
> def **init**(self, in_c=4, out_c=3, only_residual=True):

Yes, i did. Are  the inc and outc variable or fixed. I just use like this in my training code.
![微信图片_20190802144753](https://user-images.githubusercontent.com/33507581/62350228-b0c2e400-b534-11e9-9cd2-426e643ad3f4.png)

**Comment by dochenms** [comment]
if your in_c is set as 4, but according to the errors you post, why you feed batch input with  channel 3 instead.....

**Comment by l172293793** [comment]
> if your in_c is set as 4, but according to the errors you post, why you feed batch input with channel 3 instead.....

That's what I want to know...

**Comment by dochenms** [comment]
............ no words here...................

could you post your code scripts here?

**Comment by l172293793** [comment]
> could you post your code scripts here?



[新建文本文档.txt](https://github.com/cddlyf/GCANet/files/3459972/default.txt)

**Comment by dochenms** [comment]
obviously, get_item function in class Dataset  return an image with channel 3

**Comment by dochenms** [comment]
please send me your email, I will directly send my code to you.

**Comment by l172293793** [comment]
> please send me your email, I will directly send my code to you.

172293793@qq.com
Thank you so much.
